version: '3.8'
services:

  db:
    image: mongo:8.2.2
    container_name: mongo
    volumes:
    - ./backend/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: productInSupermarket
    ports:
      - 27017:27017

  my_express:
    build: ./backend
    image: my_express:1.0.0
    container_name: my_express
    restart: always
    ports:
      - 8002:5175
    volumes:
      - ./backend:/app
    depends_on:
      - db
  
  supermarket_frontend:
    build: ./frontend
    image: supermarket_frontend:1.0.0
    container_name: supermarket_frontend
    restart: always
    environment:
      WATCHPACK_POLLING: true
      CHOKIDAR_USEPOLLING: true
    ports:
      - 5176:5173
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - my_express